In [14]:
import numpy as np

In [44]:
#將下兩列array存成npz檔
array1 = np.array(range(30))
array2 = np.array([2,3,5])
np.savez('array_save.npz',array1,array2)

In [50]:
#讀取剛剛的 npz 檔，加入下列 array 一起存成新的 npz 檔
A=np.load('array_save.npz')
print(A['arr_0'])
print(A['arr_1'])
print('---------------------------------')
array3 = np.arange(3)
np.savez('array_new.npz',A['arr_0'],A['arr_1'],array3)
B = np.load('array_new.npz')
print(B['arr_0'])
print(B['arr_1'])
print(B['arr_2'])


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]
---------------------------------
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]
[0 1 2]
