In [52]:
import numpy as np

In [53]:
#array1 = np.array([[10, 8], [3, 5]])
#運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
array1 = np.array([[10,8],[3,5]])
array1_inv = np.linalg.inv(array1)
print(np.dot(array1,array1_inv))
print('是單位矩陣')

[[1. 0.]
 [0. 1.]]
是單位矩陣


In [54]:
#運用上列array計算特徵值、特徵向量?
w, v = np.linalg.eig(array1)
print('特徵值')
print(w)
print('特徵向量')
print(v)

特徵值
[13.  2.]
特徵向量
[[ 0.93632918 -0.70710678]
 [ 0.35112344  0.70710678]]


In [57]:
#運用上列array計算SVD
u, s, vh= np.linalg.svd(array1)
print('u')
print(u)
print('s')
print(s)
print('vh')
print(vh)

u
[[-0.91663818 -0.39971796]
 [-0.39971796  0.91663818]]
s
[13.94721714  1.86417116]
vh
[[-0.74319741 -0.6690722 ]
 [-0.6690722   0.74319741]]
